dist: focal
language: cpp

sudo: required # only for faster builds

# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - sh build-libressl.sh && sh build.sh
  
