language: cpp

matrix:
  include:
    - compiler: clang
      os: osx
      env: ARCH=native
    - compiler: gcc
      os: osx
      env: ARCH=native
    - compiler: clang
      os: linux
      env: ARCH=native
      dist: focal
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=native
      dist: focal
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=mingw32
      dist: focal
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=mingw64
      dist: focal
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=arm32
      dist: focal
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=arm64
      dist: focal
      sudo: required

# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - sh build-libressl.sh && sh build.sh
  
